# Generated by Django 3.1.6 on 2021-02-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_type', models.CharField(help_text='Enter type of stock that you own', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(help_text='Enter your symbol', max_length=20)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('value_at_buy', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type_of_stock', models.ManyToManyField(help_text='Select type of this stock', to='stocks.StockType')),
            ],
        ),
    ]
