# Generated by Django 3.1.6 on 2021-02-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(help_text='Enter name of the stock', max_length=100),
        ),
    ]
