# Generated by Django 3.1.6 on 2021-02-11 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210210_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular stock', primary_key=True, serialize=False),
        ),
    ]
