# Generated by Django 3.1.6 on 2021-02-10 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title', max_length=150)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='library')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a genre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular media', primary_key=True, serialize=False)),
                ('rating', models.CharField(blank=True, choices=[('10', '10stars'), ('09', '9stars'), ('08', '8stars'), ('07', '7stars'), ('06', '6stars'), ('05', '5stars'), ('04', '4stars'), ('03', '3stars'), ('02', '2stars'), ('01', '1stars'), ('00', '0stars')], default='00', help_text='Rating of your media', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.ManyToManyField(help_text='Select genres for this media', to='catalog.Genres'),
        ),
    ]
